# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToDoListProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftGen'
  pod 'SwiftLint'
  pod 'SQLite.swift', '~> 0.14.0'

  # Pods for ToDoListProject

  target 'ToDoListProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToDoListProjectUITests' do
    # Pods for testing
  end

end
